export const fieldsArray = [
    "Approval Number"
    ,"CR"
    ,"Change Driver"
    ,"Change Title"
    ,"Cost"
    ,"ED&T"
    ,"Owner"
    ,"PDL Impact"
    ,"PMT"
    ,"Part Number"
    ,"TVM Binning"
    ,"VO Labor Impact"
    ,"VO Tooling & Facilities"
    ,"Vendor Tooling"
    ,"Weight Impact"
]